# -*- coding: utf-8 -*-
"""crop_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-qUDRk2VVajQip0C0T8a4BEYSZmk38n

# Sistema de recomendação de cultivo

## 🧠Business Understanding

### 💼 Contexto

A empresa AgroIntelliTech (Fictícia), especializada em soluções de agricultura de precisão, está desenvolvendo um sistema inteligente para recomendar a cultura ideal para cada área de cultivo. O objetivo é ajudar agricultores a maximizar o rendimento agrícola com base em variáveis ambientais e químicas do solo, reduzindo riscos e melhorando a eficiência do plantio.

### 🎯 Objetivo do Projeto

Construir um modelo de recomendação que, a partir de características do solo e clima (como N, P, K, pH, temperatura, umidade e precipitação), indique a cultura agrícola mais apropriada para determinada localidade.

## 📊 Data Understanding

### 📁 Descrição do Conjunto de Dados

O dataset contém 8 colunas com os seguintes atributos:

- N, P, K: Níveis de nitrogênio, fósforo e potássio no solo (macronutrientes essenciais para o crescimento das plantas).

- temperature: Temperatura média (°C).

- humidity: Umidade relativa do ar (%).

- ph: Nível de acidez do solo.

- rainfall: Quantidade média de chuva (mm).

- label: Cultura agrícola recomendada (alvo a ser previsto).

### EDA

#### Setup
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, scale, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline

import joblib

"""#### Carregando dados"""

df = pd.read_csv('Crop_recommendation.csv')
df.head()

"""#### Análise dos dados"""

df.info()

df.describe()

# Dados faltantes
df.isna().sum().sort_values(ascending=False)

# Dados duplicados
df.duplicated().sum().any()

# Distribuição das classes (cultivos)
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='label')
plt.xticks(rotation=90)
plt.title("Distribuição dos Cultivos")
plt.show()

df.drop('label', axis = 1).apply(scale).plot.box(figsize=(12,8))

"""Insigths
- O dataset não possui dados faltantes ou duplicados;
- Possui alguns outliers, porém nada ao extremo, vamos continuar com os dados pois deve-se considerar a variabilidade climática da região em estudo.
- Distribuição das classes de forma totalmente balanceada.

#### Data Preparation
"""

X = df.drop('label', axis=1)
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Normalização dos dados de treino
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# LabelEncoder apenas para y
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# Contagem de classes
class_counts = pd.Series(y_train).value_counts()

# Porcentagens
class_percent = pd.Series(y_train).value_counts(normalize=True) * 100

pd.DataFrame({
    'Contagem': class_counts,
    'Porcentagem (%)': class_percent.round(2)  # 2 casas decimais
}).T

"""#### Modelagem dos dados"""

#Modelo: Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)

#modelo: SVM
svm = SVC(kernel='rbf', random_state=42)
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)

#modelo: redes neurais mlp
mlp = MLPClassifier(hidden_layer_sizes=(64, 32),
                   activation='relu',
                   solver='adam',
                   max_iter=500,
                   random_state=42)

# Treinar
mlp.fit(X_train_scaled, y_train)

# Prever
y_pred_mlp = mlp.predict(X_test_scaled)

"""#### Avaliação dos resultados"""

# Dicionário para armazenar os resultados
results = {}

# Função para extrair métricas do classification report
def get_metrics_report(y_true, y_pred):
    report = classification_report(y_true, y_pred, output_dict=True)
    metrics = {
        'accuracy': report['accuracy'],
        'macro_avg_precision': report['macro avg']['precision'],
        'macro_avg_recall': report['macro avg']['recall'],
        'macro_avg_f1': report['macro avg']['f1-score']
    }
    return metrics

# Adicionando resultados de cada modelo ao dicionário
results['Random Forest'] = get_metrics_report(y_test, y_pred_rf)
results['SVM'] = get_metrics_report(y_test, y_pred_svm)
results['MLP'] = get_metrics_report(y_test, y_pred_mlp)

# Criar DataFrame comparativo
df_comparativo = pd.DataFrame(results).T
df_comparativo = df_comparativo.sort_values('accuracy', ascending=False)

# Exibir o DataFrame
print("Comparativo de Desempenho dos Modelos:")
df_comparativo

"""#### Pipeline"""

pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Normalização
    ('classifier', RandomForestClassifier(random_state=42))  # Modelo
])

#Treino
pipeline.fit(X_train, y_train)

#Salvando a pipeline
joblib.dump(pipeline, 'crop_recommendation_pipeline.joblib')
joblib.dump(le, 'label_encoder.joblib')

import joblib

# Carregar pipeline e encoder
pipeline = joblib.load('crop_recommendation_pipeline.joblib')
le = joblib.load('label_encoder.joblib')

# Nova amostra (N, P, K, temperature, humidity, ph, rainfall)
new_sample = [[90, 42, 43, 20.8, 82, 6.5, 203]]  # Valores de exemplo

# Fazer predição
predicted_class = pipeline.predict(new_sample)
print(f"Recomendação: {predicted_class}")

